<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE grammatik [
<!ELEMENT grammatik (name,n,t,s,p)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT n (#PCDATA)>
<!ELEMENT t (#PCDATA)>
<!ELEMENT s (#PCDATA)>
<!ELEMENT p (zeile+)>
<!ELEMENT zeile (zelle+)>
<!ELEMENT zelle (#PCDATA)> ]>


<grammatik>
    <name>Grammatik</name>
    <n>S;A;B;C;D;E</n>
    <t>a;b</t>
    <s>S</s>
    <p>
        <zeile>
            <zelle>S</zelle>
            <zelle>aAa</zelle>
            <zelle>bBb</zelle>
            <zelle>A</zelle>
            <zelle>/Eps</zelle>
        </zeile>
        <zeile>
            <zelle>A</zelle>
            <zelle>C</zelle>
            <zelle>a</zelle>
        </zeile>
        <zeile>
            <zelle>B</zelle>
            <zelle>b</zelle>
        </zeile>
        <zeile>
            <zelle>C</zelle>
            <zelle>CDE</zelle>
            <zelle>/Eps</zelle>
        </zeile>
        <zeile>
            <zelle>D</zelle>
            <zelle>A</zelle>
            <zelle>B</zelle>
            <zelle>ab</zelle>
        </zeile>
        <zeile>
            <zelle>E</zelle>
            <zelle>B</zelle>
            <zelle>A</zelle>
        </zeile>
    </p>
</grammatik>